# Copyright 2026 Kabuqina Contributors
# SPDX-License-Identifier: Apache-2.0
"""Golden-transcript characterization harness for ``AIAgent.run_conversation``.

This is the behavioral safety net for the consolidate refactor (phase 3) and the
ReAct→LangGraph re-platform (phase 3.5): see
``docs/superpowers/specs/2026-06-24-consolidate-and-langgraph-replatform-plan.md``.
"New graph ≡ old loop" and "consolidated dispatch ≡ old dispatch" cannot be
proven by inspection — so we pin the *observable* behavior of the loop with
replayable transcripts and diff against committed snapshots.

Design — mock the **transport boundary, not the loop**:

* A scripted sequence of model turns is fed in at ``_interruptible_api_call``
  (chat-completions) or ``_anthropic_messages_create`` (anthropic-messages), one
  turn per API call. The real loop runs unchanged in between.
* Registry tools are stubbed at the single shared primitive both the sequential
  and concurrent dispatch paths call (``run_agent.handle_function_call``), so
  tool results are canned and deterministic and the dispatch decision is real.
* The conversation runs fully hermetically — no network, no disk, no DB — and we
  snapshot the observable contract: the result dict, the normalized message
  trajectory, tool invocations, usage/cost, the rows that *would* be persisted,
  and any stream-callback deltas.

The transcript schema (one JSON file per case under ``golden/``)::

    {
      "name": "...", "description": "...",
      "agent": {"api_mode": "chat_completions", "provider": "openrouter",
                "model": "golden/test-model", "base_url": "https://api.openai.com/v1"},
      "user_message": "...",
      "tools": ["web_search"],                 # tool schemas exposed to the agent
      "tool_results": {"web_search": "{...}"},  # canned result string per tool
      "model_turns": [                          # one entry per API call
        {"content": null, "finish_reason": "tool_calls",
         "tool_calls": [{"id": "call_1", "name": "web_search", "arguments": "{...}"}],
         "usage": {"prompt_tokens": 100, "completion_tokens": 10, "total_tokens": 110}},
        {"content": "answer", "finish_reason": "stop", "usage": {...}}
      ],
      "expected": { ...captured snapshot... }   # generated by GOLDEN_RECORD=1
    }
"""

from __future__ import annotations

import contextlib
import json
import threading
from types import SimpleNamespace
from typing import Any, Dict, List
from unittest.mock import MagicMock, patch

# Fixed, deterministic identity so persisted rows / session tags never vary.
GOLDEN_SESSION_ID = "golden-session-0001"

# Covered branches (fixtures under golden/) — the full phase-0 set:
# plain text, single-tool (sequential), parallel multi-tool (concurrent),
# anthropic_messages text, interrupt, steer, unknown-tool rejection,
# max-iterations (toolless summary via the raw client), provider fallback, and
# preflight compression (compressor stubbed; _compress_context runs for real,
# rotating the session — its random new id is not snapshotted, so it stays
# deterministic).


# ── Fakes mirroring the production client surfaces (see
#    tests/run_agent/test_context_token_tracking.py) ──────────────────────────


class _FakeOpenAIClient:
    api_key = "golden-openai-key"
    base_url = "https://api.openai.com/v1"
    _default_headers = None

    def close(self):  # pragma: no cover - trivial
        pass


class _FakeAnthropicClient:
    def close(self):  # pragma: no cover - trivial
        pass


def _tool_def(name: str) -> Dict[str, Any]:
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": f"{name} (golden stub)",
            "parameters": {"type": "object", "properties": {}},
        },
    }


# ── Scripted transport + tool stub ───────────────────────────────────────────


class _ScriptedTransport:
    """Returns the next scripted model turn per call; records the call count.

    A turn may carry an ``action`` ("interrupt"/"steer", applied to ``self.agent``
    before the response is returned, so the loop observes the signal mid-turn) and
    ``invalid: true`` (returns ``None`` to drive the empty/malformed-response →
    fallback path).
    """

    def __init__(self, turns: List[Dict[str, Any]], builder, model: str):
        self._turns = turns
        self._builder = builder
        self._model = model
        self.calls = 0
        self.agent = None  # set by replay_transcript after construction

    def __call__(self, *args, **kwargs):
        if self.calls >= len(self._turns):
            raise AssertionError(
                f"loop requested model turn #{self.calls + 1} but the transcript "
                f"only scripts {len(self._turns)} turn(s) — the loop did not "
                f"terminate where the fixture expected"
            )
        turn = self._turns[self.calls]
        self.calls += 1

        action = turn.get("action")
        if action == "interrupt":
            self.agent.interrupt(turn.get("action_text"))
        elif action == "steer":
            self.agent.steer(turn.get("action_text", ""))

        if turn.get("invalid"):
            return None
        return self._builder(turn, self._model)


class _FakeChatClient(_FakeOpenAIClient):
    """Fake OpenAI client whose ``chat.completions.create`` returns a fixed
    response — used for the max-iterations summary call, which bypasses
    ``_interruptible_api_call`` and hits ``self.client`` directly."""

    def __init__(self, summary_response):
        self._summary = summary_response
        self.chat = SimpleNamespace(
            completions=SimpleNamespace(create=self._create)
        )

    def _create(self, **kwargs):
        if self._summary is None:
            raise AssertionError(
                "the loop made a direct client.chat.completions.create() call "
                "(e.g. the max-iterations summary) but the transcript has no "
                "'summary_response'"
            )
        return self._summary


class _ToolStub:
    """Replaces ``handle_function_call``; records invocations, returns canned results."""

    def __init__(self, results: Dict[str, str]):
        self._results = results
        self.calls: List[Dict[str, Any]] = []
        self._lock = threading.Lock()

    def __call__(self, function_name, function_args, *args, **kwargs):
        with self._lock:
            self.calls.append({"name": function_name, "arguments": function_args})
        if function_name in self._results:
            return self._results[function_name]
        return json.dumps({"ok": True, "tool": function_name}, ensure_ascii=False)


class _CompressStub:
    """Replaces ``context_compressor.compress``; records calls and returns a
    deterministic compressed history (the real compressor makes model calls and
    is covered by tests/agent/test_context_compressor.py — here we only
    characterize the loop's *integration* with it)."""

    def __init__(self, compressed_history):
        self._compressed = compressed_history
        self.calls = 0

    def __call__(self, messages, *args, **kwargs):
        self.calls += 1
        return [dict(m) for m in self._compressed]


def _chat_response(turn: Dict[str, Any], model: str):
    """Build an OpenAI ChatCompletion-shaped response (SimpleNamespace)."""
    tool_calls = None
    if turn.get("tool_calls"):
        tool_calls = [
            SimpleNamespace(
                id=tc.get("id") or f"call_{i}",
                type="function",
                function=SimpleNamespace(
                    name=tc["name"], arguments=tc.get("arguments", "{}")
                ),
            )
            for i, tc in enumerate(turn["tool_calls"])
        ]
    msg = SimpleNamespace(
        role="assistant",
        content=turn.get("content"),
        tool_calls=tool_calls,
        reasoning_content=turn.get("reasoning_content"),
    )
    if turn.get("reasoning") is not None:
        msg.reasoning = turn["reasoning"]
    choice = SimpleNamespace(
        index=0, message=msg, finish_reason=turn.get("finish_reason", "stop")
    )
    usage = turn.get("usage")
    return SimpleNamespace(
        choices=[choice],
        model=model,
        usage=SimpleNamespace(**usage) if usage else None,
    )


def _anthropic_response(turn: Dict[str, Any], model: str):
    """Build an Anthropic Messages-shaped response (SimpleNamespace)."""
    blocks = []
    if turn.get("content"):
        blocks.append(SimpleNamespace(type="text", text=turn["content"]))
    for tc in turn.get("tool_calls") or []:
        blocks.append(
            SimpleNamespace(
                type="tool_use",
                id=tc.get("id"),
                name=tc["name"],
                input=json.loads(tc.get("arguments", "{}")),
            )
        )
    usage = turn.get("usage") or {"input_tokens": 0, "output_tokens": 0}
    return SimpleNamespace(
        content=blocks,
        stop_reason=turn.get("stop_reason", "end_turn"),
        usage=SimpleNamespace(**usage),
        model=model,
    )


# ── Snapshot normalization (everything below must be deterministic) ───────────


def _normalize_tool_calls(tcs) -> List[Dict[str, Any]]:
    """Reduce tool_calls to the stable {id, name, arguments} shape.

    Drops volatile internal fields like ``response_item_id`` (a per-run random
    ``fc_<hex>`` id) and ``call_id``/``type`` duplicates so snapshots are stable.
    """
    norm = []
    for tc in tcs or []:
        if isinstance(tc, dict):
            fn = tc.get("function", {}) or {}
            norm.append(
                {
                    "id": tc.get("id"),
                    "name": fn.get("name", tc.get("name")),
                    "arguments": fn.get("arguments", tc.get("arguments")),
                }
            )
        else:  # object form
            norm.append(
                {
                    "id": getattr(tc, "id", None),
                    "name": tc.function.name,
                    "arguments": tc.function.arguments,
                }
            )
    return norm


def _normalize_messages(messages: List[Any]) -> List[Dict[str, Any]]:
    """Stable subset of the conversation; drops the env-dependent system prompt."""
    out: List[Dict[str, Any]] = []
    for m in messages:
        if not isinstance(m, dict):
            continue
        role = m.get("role")
        if role == "system":
            continue  # contains today's date / cwd / tool list — not stable
        entry: Dict[str, Any] = {"role": role}
        if m.get("content") is not None:
            entry["content"] = m.get("content")
        if m.get("tool_calls"):
            entry["tool_calls"] = _normalize_tool_calls(m.get("tool_calls"))
        for key in ("tool_call_id", "tool_name", "finish_reason", "reasoning"):
            if m.get(key):
                entry[key] = m[key]
        out.append(entry)
    return out


def _normalize_persisted(session_db) -> List[Dict[str, Any]]:
    """The rows the agent handed to ``append_message`` (what *would* persist)."""
    append = getattr(session_db, "append_message", None)
    if append is None or not hasattr(append, "call_args_list"):
        return []
    rows = []
    for call in append.call_args_list:
        kw = call.kwargs
        tcs = kw.get("tool_calls")
        rows.append(
            {
                "role": kw.get("role"),
                "content": kw.get("content"),
                "tool_name": kw.get("tool_name"),
                "tool_call_id": kw.get("tool_call_id"),
                "finish_reason": kw.get("finish_reason"),
                "tool_calls": _normalize_tool_calls(tcs) if tcs else None,
            }
        )
    return rows


def _snapshot(result, agent, tool_stub, transport, stream_log) -> Dict[str, Any]:
    return {
        "result": {
            "final_response": result.get("final_response"),
            "completed": result.get("completed"),
            "partial": result.get("partial"),
            "interrupted": result.get("interrupted"),
            "api_calls": result.get("api_calls"),
            "model": result.get("model"),
            "provider": result.get("provider"),
            "interrupt_message": result.get("interrupt_message"),
            "pending_steer": result.get("pending_steer"),
        },
        "usage": {
            "input_tokens": result.get("input_tokens"),
            "output_tokens": result.get("output_tokens"),
            "prompt_tokens": result.get("prompt_tokens"),
            "completion_tokens": result.get("completion_tokens"),
            "total_tokens": result.get("total_tokens"),
            "cache_read_tokens": result.get("cache_read_tokens"),
            "cache_write_tokens": result.get("cache_write_tokens"),
            "reasoning_tokens": result.get("reasoning_tokens"),
            "last_prompt_tokens": result.get("last_prompt_tokens"),
            "estimated_cost_usd": result.get("estimated_cost_usd"),
            "cost_status": result.get("cost_status"),
            "cost_source": result.get("cost_source"),
        },
        "messages": _normalize_messages(result.get("messages", [])),
        # Sorted so the concurrent path's thread-completion order can't flip it;
        # the message trajectory above still captures real ordering.
        "tool_invocations": sorted(
            tool_stub.calls,
            key=lambda c: (c["name"], json.dumps(c["arguments"], sort_keys=True)),
        ),
        "model_turns_consumed": transport.calls,
        "persisted_db_messages": _normalize_persisted(agent._session_db),
        "stream_deltas": list(stream_log),
    }


@contextlib.contextmanager
def _patches(tool_names, tool_stub, api_mode):
    import run_agent

    stack = contextlib.ExitStack()
    stack.enter_context(
        patch.object(
            run_agent,
            "get_tool_definitions",
            lambda **kw: [_tool_def(n) for n in tool_names],
        )
    )
    stack.enter_context(
        patch.object(run_agent, "check_toolset_requirements", lambda *a, **k: {})
    )
    stack.enter_context(
        patch.object(run_agent, "OpenAI", lambda **kw: _FakeOpenAIClient())
    )
    stack.enter_context(
        patch.object(run_agent, "handle_function_call", tool_stub)
    )
    if api_mode == "anthropic_messages":
        import providers.anthropic as anthropic_provider

        stack.enter_context(
            patch.object(
                anthropic_provider,
                "build_anthropic_client",
                lambda *a, **k: _FakeAnthropicClient(),
            )
        )
    try:
        yield
    finally:
        stack.close()


@contextlib.contextmanager
def _fallback_patch(fallback_model):
    """Make ``resolve_provider_client`` hand the fallback path a fake client.

    No-op unless the transcript configures a fallback — without it, an unknown
    fallback provider would just no-op (provider not configured) and never
    activate, so the fallback branch couldn't be characterized.
    """
    if not fallback_model:
        yield
        return
    import providers.chat_completions as cc

    fb = fallback_model[0] if isinstance(fallback_model, list) else fallback_model
    fb_model = (fb or {}).get("model", "fallback-model")
    fb_base = (fb or {}).get("base_url") or "https://fallback.example/v1"
    fake = SimpleNamespace(
        base_url=fb_base,
        api_key="fallback-key",
        _default_headers=None,
        close=lambda: None,
    )
    with patch.object(cc, "resolve_provider_client", lambda *a, **k: (fake, fb_model)):
        yield


def replay_transcript(spec: Dict[str, Any]) -> Dict[str, Any]:
    """Replay one transcript against a real ``AIAgent`` and return the snapshot."""
    import run_agent

    cfg = spec.get("agent", {})
    api_mode = cfg.get("api_mode", "chat_completions")
    provider = cfg.get("provider", "openrouter")
    model = cfg.get("model", "golden/test-model")
    base_url = cfg.get("base_url", "https://api.openai.com/v1")

    tool_names = spec.get("tools", [])
    tool_stub = _ToolStub(spec.get("tool_results", {}))
    builder = _anthropic_response if api_mode == "anthropic_messages" else _chat_response
    transport = _ScriptedTransport(spec.get("model_turns", []), builder, model)
    stream_log: List[str] = []

    # Optional summary response for the max-iterations path (direct client call).
    summary_spec = spec.get("summary_response")
    summary_response = _chat_response(summary_spec, model) if summary_spec else None

    # Optional preflight-compression config.
    compression = spec.get("compression")
    compress_stub = (
        _CompressStub(compression.get("compressed_history", []))
        if compression
        else None
    )
    conversation_history = spec.get("conversation_history")

    extra_kwargs = {}
    if "max_iterations" in cfg:
        extra_kwargs["max_iterations"] = cfg["max_iterations"]
    if cfg.get("fallback_model"):
        extra_kwargs["fallback_model"] = cfg["fallback_model"]

    with _patches(tool_names, tool_stub, api_mode), _fallback_patch(cfg.get("fallback_model")):
        agent = run_agent.AIAgent(
            api_key="golden-key",
            base_url=base_url,
            provider=provider,
            api_mode=api_mode,
            model=model,
            quiet_mode=True,
            skip_context_files=True,
            skip_memory=True,
            **extra_kwargs,
        )
        # Determinism + hermeticity.
        agent.session_id = GOLDEN_SESSION_ID
        agent.api_mode = api_mode
        agent.provider = provider
        agent._disable_streaming = True  # force the non-streaming path
        agent._session_db = MagicMock()  # capture would-be-persisted rows
        agent._last_flushed_db_idx = 0
        agent._save_session_log = lambda *a, **k: None  # no JSON log on disk
        agent._save_trajectory = lambda *a, **k: None  # no trajectory on disk
        if summary_response is not None:
            agent.client = _FakeChatClient(summary_response)

        if compression is not None:
            # Drive the preflight-compression path deterministically: lower the
            # protect window + threshold so a small history trips it, and stub
            # the model-calling compressor with a fixed compressed history.
            agent.compression_enabled = True
            cc = agent.context_compressor
            cc.protect_first_n = compression.get("protect_first_n", 1)
            cc.protect_last_n = compression.get("protect_last_n", 1)
            cc.threshold_tokens = compression.get("threshold_tokens", 5)
            cc.compress = compress_stub

        transport.agent = agent
        if api_mode == "anthropic_messages":
            agent._anthropic_messages_create = transport
        else:
            agent._interruptible_api_call = transport

        result = agent.run_conversation(
            spec["user_message"],
            conversation_history=conversation_history,
            stream_callback=lambda text: stream_log.append(text),
        )

    if compress_stub is not None:
        assert compress_stub.calls > 0, (
            "compression transcript did not trip the preflight compressor — check "
            "conversation_history length vs protect_first_n+protect_last_n+1 and "
            "threshold_tokens"
        )

    return _snapshot(result, agent, tool_stub, transport, stream_log)
