# Copyright 2026 Kabuqina Contributors
# SPDX-License-Identifier: Apache-2.0
"""Golden-transcript characterization harness for ``AIAgent.run_conversation``.

This is the behavioral safety net for the consolidate refactor (phase 3) and the
ReAct→LangGraph re-platform (phase 3.5): see
``docs/superpowers/specs/2026-06-24-consolidate-and-langgraph-replatform-plan.md``.
"New graph ≡ old loop" and "consolidated dispatch ≡ old dispatch" cannot be
proven by inspection — so we pin the *observable* behavior of the loop with
replayable transcripts and diff against committed snapshots.

Design — mock the **transport boundary, not the loop**:

* A scripted sequence of model turns is fed in at ``_interruptible_api_call``
  (chat-completions) or ``_anthropic_messages_create`` (anthropic-messages), one
  turn per API call. The real loop runs unchanged in between.
* Registry tools are stubbed at the single shared primitive both the sequential
  and concurrent dispatch paths call (``run_agent.handle_function_call``), so
  tool results are canned and deterministic and the dispatch decision is real.
* The conversation runs fully hermetically — no network, no disk, no DB — and we
  snapshot the observable contract: the result dict, the normalized message
  trajectory, tool invocations, usage/cost, the rows that *would* be persisted,
  and any stream-callback deltas.

The transcript schema (one JSON file per case under ``golden/``)::

    {
      "name": "...", "description": "...",
      "agent": {"api_mode": "chat_completions", "provider": "openrouter",
                "model": "golden/test-model", "base_url": "https://api.openai.com/v1"},
      "user_message": "...",
      "tools": ["web_search"],                 # tool schemas exposed to the agent
      "tool_results": {"web_search": "{...}"},  # canned result string per tool
      "model_turns": [                          # one entry per API call
        {"content": null, "finish_reason": "tool_calls",
         "tool_calls": [{"id": "call_1", "name": "web_search", "arguments": "{...}"}],
         "usage": {"prompt_tokens": 100, "completion_tokens": 10, "total_tokens": 110}},
        {"content": "answer", "finish_reason": "stop", "usage": {...}}
      ],
      "expected": { ...captured snapshot... }   # generated by GOLDEN_RECORD=1
    }
"""

from __future__ import annotations

import contextlib
import json
import threading
from types import SimpleNamespace
from typing import Any, Dict, List
from unittest.mock import MagicMock, patch

# Fixed, deterministic identity so persisted rows / session tags never vary.
GOLDEN_SESSION_ID = "golden-session-0001"

# Fixed task id so ``effective_task_id`` (otherwise ``str(uuid.uuid4())``) and any
# task-scoped hook payload / cleanup id stay deterministic across runs.
GOLDEN_TASK_ID = "golden-task-0001"

# Retry/attempt limits frozen by Phase 3.5 Task 2. Exhaustion fixtures declare
# only the limits they depend on; validation happens before the loop consumes a
# scripted turn so drift fails with a targeted message.
RETRY_ASSUMPTIONS = {
    "api_max_retries": 3,
    "max_compression_attempts": 3,
    "text_continuation_attempts": 3,
    "truncated_tool_call_retries": 1,
    "incomplete_scratchpad_retries": 2,
    "unknown_tool_retries": 3,
}

# Hook payload fields that are wall-clock- or system-prompt-dependent and must
# never enter a frozen snapshot. ``api_duration`` is elapsed seconds;
# ``approx_input_tokens`` / ``request_char_count`` are measured over the full
# request payload, whose system prompt carries today's date / cwd.
_VOLATILE_HOOK_KEYS = frozenset(
    {"api_duration", "approx_input_tokens", "request_char_count"}
)

# Covered branches (fixtures under golden/) — the full phase-0 set:
# plain text, single-tool (sequential), parallel multi-tool (concurrent),
# anthropic_messages text, interrupt, steer, unknown-tool rejection,
# max-iterations (toolless summary via the raw client), provider fallback, and
# preflight compression (compressor stubbed; _compress_context runs for real,
# rotating the session — its random new id is not snapshotted, so it stays
# deterministic).


# ── Fakes mirroring the production client surfaces (see
#    tests/run_agent/test_context_token_tracking.py) ──────────────────────────


class _FakeOpenAIClient:
    api_key = "golden-openai-key"
    base_url = "https://api.openai.com/v1"
    _default_headers = None

    def close(self):  # pragma: no cover - trivial
        pass


class _FakeAnthropicClient:
    def close(self):  # pragma: no cover - trivial
        pass


def _tool_def(name: str) -> Dict[str, Any]:
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": f"{name} (golden stub)",
            "parameters": {"type": "object", "properties": {}},
        },
    }


# ── Scripted transport + tool stub ───────────────────────────────────────────


class _ScriptedTransport:
    """Returns the next scripted model turn per call; records the call count.

    A turn may carry an ``action`` ("interrupt"/"steer", applied to ``self.agent``
    before the response is returned, so the loop observes the signal mid-turn) and
    ``invalid: true`` (returns ``None`` to drive the empty/malformed-response →
    fallback path).
    """

    def __init__(self, turns: List[Dict[str, Any]], builder, model: str):
        self._turns = turns
        self._builder = builder
        self._model = model
        self.calls = 0
        self.agent = None  # set by replay_transcript after construction

    def __call__(self, *args, **kwargs):
        if self.calls >= len(self._turns):
            raise AssertionError(
                f"loop requested model turn #{self.calls + 1} but the transcript "
                f"only scripts {len(self._turns)} turn(s) — the loop did not "
                f"terminate where the fixture expected"
            )
        turn = self._turns[self.calls]
        self.calls += 1

        action = turn.get("action")
        if action == "interrupt":
            self.agent.interrupt(turn.get("action_text"))
        elif action == "steer":
            self.agent.steer(turn.get("action_text", ""))

        if turn.get("invalid"):
            return None
        if error_spec := turn.get("raise"):
            error_type = error_spec.get("type", "api_error")
            error_cls = ValueError if error_type == "value_error" else Exception
            error = error_cls(error_spec.get("message", error_type))
            for attr in ("status_code", "body"):
                if attr in error_spec:
                    setattr(error, attr, error_spec[attr])
            if "response_headers" in error_spec:
                error.response = SimpleNamespace(
                    headers=dict(error_spec["response_headers"])
                )
            raise error
        return self._builder(turn, self._model)


class _FakeChatClient(_FakeOpenAIClient):
    """Fake OpenAI client whose ``chat.completions.create`` returns a fixed
    response — used for the max-iterations summary call, which bypasses
    ``_interruptible_api_call`` and hits ``self.client`` directly."""

    def __init__(self, summary_response):
        self._summary = summary_response
        self.chat = SimpleNamespace(
            completions=SimpleNamespace(create=self._create)
        )

    def _create(self, **kwargs):
        if self._summary is None:
            raise AssertionError(
                "the loop made a direct client.chat.completions.create() call "
                "(e.g. the max-iterations summary) but the transcript has no "
                "'summary_response'"
            )
        return self._summary


class _ToolStub:
    """Replaces ``handle_function_call``; records invocations, returns canned results."""

    def __init__(self, results: Dict[str, str]):
        self._results = results
        self.calls: List[Dict[str, Any]] = []
        self._lock = threading.Lock()

    def __call__(self, function_name, function_args, *args, **kwargs):
        with self._lock:
            self.calls.append({"name": function_name, "arguments": function_args})
        if function_name in self._results:
            return self._results[function_name]
        return json.dumps({"ok": True, "tool": function_name}, ensure_ascii=False)


class _CompressStub:
    """Replaces ``context_compressor.compress``; records calls and returns a
    deterministic compressed history (the real compressor makes model calls and
    is covered by tests/agent/test_context_compressor.py — here we only
    characterize the loop's *integration* with it)."""

    def __init__(self, compressed_history=None, *, sequence=None):
        if compressed_history is not None and sequence is not None:
            raise TypeError("declare compressed_history or sequence, not both")
        self._compressed = compressed_history
        self._sequence = sequence
        self.calls = 0

    def __call__(self, messages, *args, **kwargs):
        self.calls += 1
        if self._sequence is not None:
            if self.calls > len(self._sequence):
                raise AssertionError(
                    f"compressor requested output #{self.calls}, but the fixture "
                    f"only declares {len(self._sequence)} output(s)"
                )
            compressed = self._sequence[self.calls - 1]
        else:
            compressed = self._compressed or []
        return [dict(m) for m in compressed]


class _ScriptedClock:
    """Deterministic clock for retry/compression sleeps in transcript replay."""

    def __init__(self, *, interrupt_on_sleep=None, interrupt=None):
        # Keep the synthetic epoch comfortably modern so libraries that inspect
        # wall time (for certificate sanity checks) do not emit warnings.
        self._now = 2_000_000_000.0
        self._interrupt_on_sleep = interrupt_on_sleep
        self._interrupt = interrupt
        self.sleep_calls = 0

    def time(self):
        return self._now

    def sleep(self, seconds):
        self.sleep_calls += 1
        self._now += max(float(seconds), 0.001)
        if (
            self._interrupt_on_sleep == self.sleep_calls
            and self._interrupt is not None
        ):
            self._interrupt()


def _validate_retry_assumptions(assumptions: Dict[str, int]) -> None:
    """Fail before replay when a fixture's declared retry limit has drifted."""
    unknown = sorted(set(assumptions) - set(RETRY_ASSUMPTIONS))
    assert not unknown, f"unknown retry assumption(s): {', '.join(unknown)}"
    drifted = [
        f"{name}: fixture={value}, contract={RETRY_ASSUMPTIONS[name]}"
        for name, value in sorted(assumptions.items())
        if RETRY_ASSUMPTIONS[name] != value
    ]
    assert not drifted, "retry assumption drift:\n  " + "\n  ".join(drifted)


def _chat_response(turn: Dict[str, Any], model: str):
    """Build an OpenAI ChatCompletion-shaped response (SimpleNamespace)."""
    tool_calls = None
    if turn.get("tool_calls"):
        tool_calls = [
            SimpleNamespace(
                id=tc.get("id") or f"call_{i}",
                type="function",
                function=SimpleNamespace(
                    name=tc["name"], arguments=tc.get("arguments", "{}")
                ),
            )
            for i, tc in enumerate(turn["tool_calls"])
        ]
    msg = SimpleNamespace(
        role="assistant",
        content=turn.get("content"),
        tool_calls=tool_calls,
        reasoning_content=turn.get("reasoning_content"),
    )
    if turn.get("reasoning") is not None:
        msg.reasoning = turn["reasoning"]
    choice = SimpleNamespace(
        index=0, message=msg, finish_reason=turn.get("finish_reason", "stop")
    )
    usage = turn.get("usage")
    return SimpleNamespace(
        choices=[choice],
        model=model,
        usage=SimpleNamespace(**usage) if usage else None,
    )


def _anthropic_response(turn: Dict[str, Any], model: str):
    """Build an Anthropic Messages-shaped response (SimpleNamespace)."""
    blocks = []
    if turn.get("content"):
        blocks.append(SimpleNamespace(type="text", text=turn["content"]))
    for tc in turn.get("tool_calls") or []:
        blocks.append(
            SimpleNamespace(
                type="tool_use",
                id=tc.get("id"),
                name=tc["name"],
                input=json.loads(tc.get("arguments", "{}")),
            )
        )
    usage = turn.get("usage") or {"input_tokens": 0, "output_tokens": 0}
    return SimpleNamespace(
        content=blocks,
        stop_reason=turn.get("stop_reason", "end_turn"),
        usage=SimpleNamespace(**usage),
        model=model,
    )


# ── Snapshot normalization (everything below must be deterministic) ───────────


def _normalize_tool_calls(tcs) -> List[Dict[str, Any]]:
    """Reduce tool_calls to the stable {id, name, arguments} shape.

    Drops volatile internal fields like ``response_item_id`` (a per-run random
    ``fc_<hex>`` id) and ``call_id``/``type`` duplicates so snapshots are stable.
    """
    norm = []
    for tc in tcs or []:
        if isinstance(tc, dict):
            fn = tc.get("function", {}) or {}
            norm.append(
                {
                    "id": tc.get("id"),
                    "name": fn.get("name", tc.get("name")),
                    "arguments": fn.get("arguments", tc.get("arguments")),
                }
            )
        else:  # object form
            norm.append(
                {
                    "id": getattr(tc, "id", None),
                    "name": tc.function.name,
                    "arguments": tc.function.arguments,
                }
            )
    return norm


def _normalize_messages(messages: List[Any]) -> List[Dict[str, Any]]:
    """Stable subset of the conversation; drops the env-dependent system prompt."""
    out: List[Dict[str, Any]] = []
    for m in messages:
        if not isinstance(m, dict):
            continue
        role = m.get("role")
        if role == "system":
            continue  # contains today's date / cwd / tool list — not stable
        entry: Dict[str, Any] = {"role": role}
        if m.get("content") is not None:
            entry["content"] = m.get("content")
        if m.get("tool_calls"):
            entry["tool_calls"] = _normalize_tool_calls(m.get("tool_calls"))
        for key in ("tool_call_id", "tool_name", "finish_reason", "reasoning"):
            if m.get(key):
                entry[key] = m[key]
        out.append(entry)
    return out


def _normalize_persisted(session_db) -> List[Dict[str, Any]]:
    """The rows the agent handed to ``append_message`` (what *would* persist)."""
    append = getattr(session_db, "append_message", None)
    if append is None or not hasattr(append, "call_args_list"):
        return []
    rows = []
    for call in append.call_args_list:
        kw = call.kwargs
        tcs = kw.get("tool_calls")
        rows.append(
            {
                "role": kw.get("role"),
                "content": kw.get("content"),
                "tool_name": kw.get("tool_name"),
                "tool_call_id": kw.get("tool_call_id"),
                "finish_reason": kw.get("finish_reason"),
                "tool_calls": _normalize_tool_calls(tcs) if tcs else None,
            }
        )
    return rows


def _normalize_hook_kwargs(kwargs: Dict[str, Any]) -> Dict[str, Any]:
    """Deterministic view of a plugin-hook payload.

    Drops wall-clock / system-prompt-dependent fields and reduces message lists
    to the same normalized trajectory used elsewhere, so re-recording is stable.
    Any non-scalar leaf is replaced with its type name to stay JSON-serializable.
    """
    out: Dict[str, Any] = {}
    for key in sorted(kwargs):
        if key in _VOLATILE_HOOK_KEYS:
            continue
        value = kwargs[key]
        if key == "session_id":
            # Preflight compression rotates session_id to a fresh random id
            # mid-run, so hooks after it carry a non-deterministic value. Keep the
            # snapshot stable while still recording that a rotation happened.
            out[key] = "<rotated-session>" if (value and value != GOLDEN_SESSION_ID) else value
            continue
        if key in ("conversation_history", "messages") and isinstance(value, list):
            out[key] = _normalize_messages(value)
        elif isinstance(value, (str, int, float, bool)) or value is None:
            out[key] = value
        elif isinstance(value, dict):
            out[key] = {
                k: (
                    value[k]
                    if isinstance(value[k], (str, int, float, bool)) or value[k] is None
                    else type(value[k]).__name__
                )
                for k in sorted(value)
            }
        else:
            out[key] = type(value).__name__
    return out


class _HookRecorder:
    """Wraps ``hermes_cli.plugins.invoke_hook`` to record ``{hook, payload}`` in
    call order while delegating to the real dispatcher — which no-ops with no
    plugins registered, and crucially still returns the iterable that the
    ``pre_llm_call`` site consumes. Replacing (instead of wrapping) would change
    behavior; we only observe."""

    def __init__(self, real_invoke):
        self._real = real_invoke
        self.calls: List[Dict[str, Any]] = []

    def __call__(self, hook_name, *args, **kwargs):
        self.calls.append(
            {"hook": hook_name, "payload": _normalize_hook_kwargs(kwargs)}
        )
        return self._real(hook_name, *args, **kwargs)


def _snapshot(
    result,
    agent,
    tool_stub,
    transport,
    stream_log,
    hook_recorder,
    cleanup_task_ids,
    clear_interrupt_calls,
    callback_events,
    trajectory_writes,
    lifecycle_calls=None,
) -> Dict[str, Any]:
    return {
        # Exact result-key presence (adding an absent key is a behavior change).
        "result_keys": sorted(result.keys()),
        "result": {
            "final_response": result.get("final_response"),
            "completed": result.get("completed"),
            "partial": result.get("partial"),
            "interrupted": result.get("interrupted"),
            "api_calls": result.get("api_calls"),
            "model": result.get("model"),
            "provider": result.get("provider"),
            "interrupt_message": result.get("interrupt_message"),
            "pending_steer": result.get("pending_steer"),
        },
        "usage": {
            "input_tokens": result.get("input_tokens"),
            "output_tokens": result.get("output_tokens"),
            "prompt_tokens": result.get("prompt_tokens"),
            "completion_tokens": result.get("completion_tokens"),
            "total_tokens": result.get("total_tokens"),
            "cache_read_tokens": result.get("cache_read_tokens"),
            "cache_write_tokens": result.get("cache_write_tokens"),
            "reasoning_tokens": result.get("reasoning_tokens"),
            "last_prompt_tokens": result.get("last_prompt_tokens"),
            "estimated_cost_usd": result.get("estimated_cost_usd"),
            "cost_status": result.get("cost_status"),
            "cost_source": result.get("cost_source"),
        },
        "messages": _normalize_messages(result.get("messages", [])),
        # Sorted so the concurrent path's thread-completion order can't flip it;
        # the message trajectory above still captures real ordering.
        "tool_invocations": sorted(
            tool_stub.calls,
            key=lambda c: (c["name"], json.dumps(c["arguments"], sort_keys=True)),
        ),
        "model_turns_consumed": transport.calls,
        "persisted_db_messages": _normalize_persisted(agent._session_db),
        "stream_deltas": list(stream_log),
        # Unified callback stream preserves cross-channel order for lifecycle
        # status, interim assistant commentary, and text deltas.
        "callback_events": list(callback_events),
        "trajectory_writes": list(trajectory_writes),
        # Plugin hook names/order/payloads (including which hooks are *absent* on
        # an exit), and the cleanup / interrupt-clear side effects per exit.
        "hook_calls": hook_recorder.calls,
        "cleanup_task_ids": list(cleanup_task_ids),
        "clear_interrupt_calls": clear_interrupt_calls,
        # Turn-lifecycle side effects the loop runs at its prefix/finalizer that
        # the snapshot previously did not observe (Group A review remediation):
        # restore-primary-runtime, todo hydration, scrubber reset, the memory
        # nudge turn counter, external-memory sync, and background review.  A
        # graph that skips any of these diverges here.  Optional: the canonical
        # golden/differential replays capture and pass it (owning the lifecycle
        # invariant); the older per-family parity replays predate it and pass
        # nothing, so both sides compare an empty map and parity holds on the
        # other fields, exactly as before the Group A signature change.
        "lifecycle_calls": dict(lifecycle_calls or {}),
    }


@contextlib.contextmanager
def _patches(tool_names, tool_stub, api_mode, preconditions=None):
    import run_agent
    import hermes_cli.plugins as _plugins

    preconditions = preconditions or {}
    stack = contextlib.ExitStack()
    stack.enter_context(
        patch.object(
            run_agent,
            "get_tool_definitions",
            lambda **kw: [_tool_def(n) for n in tool_names],
        )
    )
    stack.enter_context(
        patch.object(run_agent, "check_toolset_requirements", lambda *a, **k: {})
    )
    stack.enter_context(
        patch.object(run_agent, "OpenAI", lambda **kw: _FakeOpenAIClient())
    )
    stack.enter_context(patch.object(run_agent, "fetch_model_metadata", lambda: {}))
    stack.enter_context(
        patch.object(run_agent, "handle_function_call", tool_stub)
    )
    if api_mode == "anthropic_messages":
        import providers.anthropic as anthropic_provider

        stack.enter_context(
            patch.object(
                anthropic_provider,
                "build_anthropic_client",
                lambda *a, **k: _FakeAnthropicClient(),
            )
        )
    if "nous_rate_guard_seconds" in preconditions:
        import providers.nous_rate_guard as nous_rate_guard

        seconds = preconditions["nous_rate_guard_seconds"]
        stack.enter_context(
            patch.object(
                nous_rate_guard,
                "nous_rate_limit_remaining",
                lambda: seconds,
            )
        )
        stack.enter_context(
            patch.object(
                nous_rate_guard,
                "format_remaining",
                lambda remaining: f"{int(remaining)}s",
            )
        )
    # Observe (don't replace) the plugin-hook dispatcher. Each call site does a
    # runtime ``from hermes_cli.plugins import invoke_hook``, so patching the
    # module attribute is seen by all six hooks.
    hook_recorder = _HookRecorder(_plugins.invoke_hook)
    stack.enter_context(patch.object(_plugins, "invoke_hook", hook_recorder))
    try:
        yield hook_recorder
    finally:
        stack.close()


@contextlib.contextmanager
def _fallback_patch(fallback_model):
    """Make ``resolve_provider_client`` hand the fallback path a fake client.

    No-op unless the transcript configures a fallback — without it, an unknown
    fallback provider would just no-op (provider not configured) and never
    activate, so the fallback branch couldn't be characterized.
    """
    if not fallback_model:
        yield
        return
    import providers.chat_completions as cc

    fb = fallback_model[0] if isinstance(fallback_model, list) else fallback_model
    fb_model = (fb or {}).get("model", "fallback-model")
    fb_base = (fb or {}).get("base_url") or "https://fallback.example/v1"
    fake = SimpleNamespace(
        base_url=fb_base,
        api_key="fallback-key",
        _default_headers=None,
        close=lambda: None,
    )
    with patch.object(cc, "resolve_provider_client", lambda *a, **k: (fake, fb_model)):
        yield


def replay_transcript(
    spec: Dict[str, Any], engine: str = "loop", usage_sink=None
) -> Dict[str, Any]:
    """Replay one transcript against a real ``AIAgent`` and return the snapshot.

    ``usage_sink`` (optional) is wired onto the agent as its ``UsageEventSink``
    so a test can assert the per-attempt usage events either engine emits.  It
    does not appear in the returned snapshot — the goldens stay sink-agnostic.

    ``engine`` selects the conversation driver:

    * ``"loop"`` runs the legacy ``AIAgent.run_conversation`` body
      (``_run_conversation_loop`` once Task 10 lands the selector);
    * ``"graph"`` runs ``AIAgent._run_conversation_graph`` (Phase 3.5 LangGraph).

    Both engines are constructed on a *fresh* agent and *fresh* scripted
    transport — never the same instance — so a parameterized equivalence test
    can compare their complete snapshots without sharing process-global state.
    """
    if engine not in ("loop", "graph"):
        raise ValueError(f"unknown engine {engine!r}; expected 'loop' or 'graph'")
    import run_agent

    _validate_retry_assumptions(spec.get("assumed_retry_counts", {}))

    cfg = spec.get("agent", {})
    preconditions = spec.get("preconditions", {})
    api_mode = cfg.get("api_mode", "chat_completions")
    provider = cfg.get("provider", "openrouter")
    model = cfg.get("model", "golden/test-model")
    base_url = cfg.get("base_url", "https://api.openai.com/v1")

    tool_names = spec.get("tools", [])
    tool_stub = _ToolStub(spec.get("tool_results", {}))
    builder = _anthropic_response if api_mode == "anthropic_messages" else _chat_response
    transport = _ScriptedTransport(spec.get("model_turns", []), builder, model)
    stream_log: List[str] = []
    callback_events: List[Dict[str, Any]] = []
    trajectory_writes: List[Dict[str, Any]] = []

    # Optional summary response for the max-iterations path (direct client call).
    summary_spec = spec.get("summary_response")
    summary_response = _chat_response(summary_spec, model) if summary_spec else None

    # Optional preflight-compression config.
    compression = spec.get("compression")
    compressed_sequence = preconditions.get("compressed_history_sequence")
    if compressed_sequence is not None:
        compress_stub = _CompressStub(sequence=compressed_sequence)
    elif compression:
        compress_stub = _CompressStub(compression.get("compressed_history", []))
    else:
        compress_stub = None
    conversation_history = spec.get("conversation_history")

    extra_kwargs = {}
    if "max_iterations" in cfg:
        extra_kwargs["max_iterations"] = cfg["max_iterations"]
    if cfg.get("fallback_model"):
        extra_kwargs["fallback_model"] = cfg["fallback_model"]

    with _patches(
        tool_names, tool_stub, api_mode, preconditions
    ) as hook_recorder, _fallback_patch(cfg.get("fallback_model")):
        agent = run_agent.AIAgent(
            api_key="golden-key",
            base_url=base_url,
            provider=provider,
            api_mode=api_mode,
            model=model,
            quiet_mode=True,
            skip_context_files=True,
            skip_memory=True,
            usage_sink=usage_sink,
            status_callback=lambda kind, message: callback_events.append(
                {"channel": "status", "kind": kind, "message": message}
            ),
            interim_assistant_callback=lambda text, **kwargs: callback_events.append(
                {
                    "channel": "interim",
                    "text": text,
                    "already_streamed": bool(kwargs.get("already_streamed")),
                }
            ),
            **extra_kwargs,
        )
        # Determinism + hermeticity.
        agent.session_id = GOLDEN_SESSION_ID
        agent.api_mode = api_mode
        agent.provider = provider
        agent._disable_streaming = True  # force the non-streaming path
        agent._session_db = MagicMock()  # capture would-be-persisted rows
        agent._last_flushed_db_idx = 0
        agent._save_session_log = lambda *a, **k: None  # no JSON log on disk
        def _record_trajectory(messages, user_query, completed):
            trajectory_writes.append(
                {
                    "messages": _normalize_messages(messages),
                    "user_query": user_query,
                    "completed": completed,
                }
            )

        agent._save_trajectory = _record_trajectory  # observe; never write disk
        if summary_response is not None:
            agent.client = _FakeChatClient(summary_response)

        if compression is not None:
            # Drive the preflight-compression path deterministically: lower the
            # protect window + threshold so a small history trips it, and stub
            # the model-calling compressor with a fixed compressed history.
            agent.compression_enabled = True
            cc = agent.context_compressor
            cc.protect_first_n = compression.get("protect_first_n", 1)
            cc.protect_last_n = compression.get("protect_last_n", 1)
            cc.threshold_tokens = compression.get("threshold_tokens", 5)
            cc.compress = compress_stub
        elif compress_stub is not None:
            agent.context_compressor.compress = compress_stub

        if "context_length" in preconditions:
            agent.context_compressor.context_length = preconditions["context_length"]

        # Observe cleanup + interrupt-clear at their boundaries (record, delegate).
        cleanup_task_ids: List[str] = []
        clear_interrupt_calls = [0]
        _real_cleanup = agent._cleanup_task_resources
        _real_clear = agent.clear_interrupt

        def _observed_cleanup(task_id, _real=_real_cleanup, _ids=cleanup_task_ids):
            _ids.append(task_id)
            return _real(task_id)

        def _observed_clear(_real=_real_clear, _box=clear_interrupt_calls):
            _box[0] += 1
            return _real()

        agent._cleanup_task_resources = _observed_cleanup
        agent.clear_interrupt = _observed_clear

        # Observe turn-lifecycle side effects (Group A review remediation): the
        # loop runs these at its turn prefix and finalizer; the graph must too.
        # Counting them at their boundaries puts them in the frozen snapshot, so
        # a graph that skips one (P1-1/P1-2) diverges from the loop here.
        lifecycle_calls = {
            "restore_primary_runtime": 0,
            "hydrate_todo_store": 0,
            "scrubber_reset": 0,
            "sync_external_memory_for_turn": 0,
            "spawn_background_review": 0,
        }
        _initial_user_turns = agent._user_turn_count

        def _count_calls(name, real):
            def _wrapped(*a, _name=name, _real=real, **k):
                lifecycle_calls[_name] += 1
                return _real(*a, **k)

            return _wrapped

        agent._restore_primary_runtime = _count_calls(
            "restore_primary_runtime", agent._restore_primary_runtime
        )
        agent._hydrate_todo_store = _count_calls(
            "hydrate_todo_store", agent._hydrate_todo_store
        )
        agent._sync_external_memory_for_turn = _count_calls(
            "sync_external_memory_for_turn", agent._sync_external_memory_for_turn
        )
        agent._spawn_background_review = _count_calls(
            "spawn_background_review", agent._spawn_background_review
        )
        _scrubber = getattr(agent, "_stream_context_scrubber", None)
        if _scrubber is not None:
            _scrubber.reset = _count_calls("scrubber_reset", _scrubber.reset)

        transport.agent = agent
        if api_mode == "anthropic_messages":
            agent._anthropic_messages_create = transport
        else:
            agent._interruptible_api_call = transport

        clock = _ScriptedClock(
            interrupt_on_sleep=preconditions.get("interrupt_on_sleep"),
            interrupt=lambda: agent.interrupt(
                preconditions.get("interrupt_text", "scripted sleep interrupt")
            ),
        )
        with (
            patch.object(run_agent.time, "time", clock.time),
            patch.object(run_agent.time, "sleep", clock.sleep),
            patch.object(
                run_agent,
                "jittered_backoff",
                lambda *a, **k: preconditions.get("backoff_seconds", 0.2),
            ),
        ):
            def _record_stream(text):
                stream_log.append(text)
                callback_events.append({"channel": "stream", "text": text})

            # Drive the engine bodies *directly* so the loop/graph
            # parameterization is independent of the strangler selector
            # (HERMES_AGENT_ENGINE / agent.engine), which the public
            # run_conversation dispatcher consults.
            _driver = (
                agent._run_conversation_graph
                if engine == "graph"
                else agent._run_conversation_loop
            )
            result = _driver(
                spec["user_message"],
                conversation_history=conversation_history,
                task_id=GOLDEN_TASK_ID,
                stream_callback=_record_stream,
            )

    if compress_stub is not None:
        assert compress_stub.calls > 0, (
            "compression transcript did not trip the preflight compressor — check "
            "conversation_history length vs protect_first_n+protect_last_n+1 and "
            "threshold_tokens"
        )

    # The memory nudge increments _user_turn_count once per turn (loop:9574);
    # observe it as a delta so a graph that skips the nudge counter diverges.
    lifecycle_calls["user_turn_count_delta"] = agent._user_turn_count - _initial_user_turns

    return _snapshot(
        result,
        agent,
        tool_stub,
        transport,
        stream_log,
        hook_recorder,
        cleanup_task_ids,
        clear_interrupt_calls[0],
        callback_events,
        trajectory_writes,
        lifecycle_calls,
    )
