// Copyright 2026 Kabuqina Contributors
// SPDX-License-Identifier: Apache-2.0

// STUDY module — spaced-repetition flashcard panel.
//
// The panel is a thin view over flashcardStore: all validation, scheduling and
// parsing live in the store (and are unit-tested there). Cards are generated by
// the agent via a bounded prompt; the student pastes the reply back here, where
// it is parsed tolerantly and merged into the local deck. Review grades feed the
// SM-2 scheduler, and a finished session can be written back into the study
// context to keep the learning loop closed.

import {
  Check,
  Eraser,
  Import,
  Layers,
  Sparkles,
  type LucideIcon,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

import { useI18n } from "../../lib/i18n";
import { WorkspaceSection } from "../workspaceSection";
import {
  FLASHCARD_EVENT,
  type Flashcard,
  type ReviewGrade,
  clearDeck,
  deckStats,
  dueCards,
  emptyDeck,
  loadDeck,
  parseFlashcards,
  reviewCard,
  saveDeck,
  upsertCards,
} from "./flashcardStore";
import { FLASHCARD_GENERATION_PROMPT } from "./studyPrompts";
import {
  STUDY_CONTEXT_FIELD_LIMIT,
  formatStudyContextForPrompt,
  loadStudyContext,
  saveStudyContext,
} from "./studyStore";

type Mode = "idle" | "review" | "done";

const GRADES: Array<{ grade: ReviewGrade; labelKey: string; tone: string }> = [
  { grade: "again", labelKey: "chat.flashcardGradeAgain", tone: "#c2410c" },
  { grade: "hard", labelKey: "chat.flashcardGradeHard", tone: "#a16207" },
  { grade: "good", labelKey: "chat.flashcardGradeGood", tone: "#2f9e8f" },
  { grade: "easy", labelKey: "chat.flashcardGradeEasy", tone: "#2563eb" },
];

export function FlashcardPanel({
  onStartPrompt,
}: {
  onStartPrompt?: (prompt: string) => void;
}) {
  const { t } = useI18n();
  const [deck, setDeck] = useState(emptyDeck);
  const [mode, setMode] = useState<Mode>("idle");
  const [queue, setQueue] = useState<Flashcard[]>([]);
  const [index, setIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [showImport, setShowImport] = useState(false);
  const [importText, setImportText] = useState("");
  const [importMsg, setImportMsg] = useState("");
  const [wroteBack, setWroteBack] = useState(false);

  useEffect(() => {
    const sync = () => setDeck(loadDeck());
    sync();
    window.addEventListener("storage", sync);
    window.addEventListener(FLASHCARD_EVENT, sync);
    return () => {
      window.removeEventListener("storage", sync);
      window.removeEventListener(FLASHCARD_EVENT, sync);
    };
  }, []);

  const stats = useMemo(() => deckStats(deck), [deck]);

  const generate = () => {
    const contextPrompt = formatStudyContextForPrompt(loadStudyContext());
    onStartPrompt?.([contextPrompt, FLASHCARD_GENERATION_PROMPT].filter(Boolean).join("\n\n"));
  };

  const runImport = () => {
    const parsed = parseFlashcards(importText);
    if (!parsed.length) {
      setImportMsg(t("chat.flashcardImportEmpty"));
      return;
    }
    const before = loadDeck();
    const merged = upsertCards(before, parsed);
    const added = merged.cards.length - before.cards.length;
    setDeck(saveDeck(merged));
    setImportText("");
    setImportMsg(t("chat.flashcardImported", { count: added }));
  };

  const startReview = () => {
    const due = dueCards(loadDeck());
    if (!due.length) return;
    setQueue(due);
    setIndex(0);
    setRevealed(false);
    setWroteBack(false);
    setMode("review");
  };

  const grade = useCallback(
    (value: ReviewGrade) => {
      const current = queue[index];
      if (!current) return;
      const updated = reviewCard(current, value);
      const next = loadDeck();
      const cards = next.cards.map((c) => (c.id === updated.id ? updated : c));
      setDeck(saveDeck({ version: 1, cards }));
      if (index + 1 >= queue.length) {
        setMode("done");
      } else {
        setIndex(index + 1);
        setRevealed(false);
      }
    },
    [index, queue],
  );

  const writeBack = () => {
    const context = loadStudyContext();
    const stamp = new Date().toISOString().slice(0, 10);
    const line = `【${stamp}】完成记忆卡片复习 ${queue.length} 张（待复习剩余 ${deckStats(loadDeck()).due}）。`;
    const progressNotes = `${line}${context.progressNotes ? `\n${context.progressNotes}` : ""}`.slice(
      0,
      STUDY_CONTEXT_FIELD_LIMIT,
    );
    saveStudyContext({ ...context, progressNotes });
    setWroteBack(true);
  };

  const clearAll = () => {
    if (typeof window !== "undefined" && !window.confirm(t("chat.flashcardClearConfirm"))) return;
    setDeck(clearDeck());
    setMode("idle");
    setQueue([]);
    setIndex(0);
  };

  const current = queue[index];

  return (
    <WorkspaceSection
      sectionId="workspace.flashcards"
      title={t("chat.flashcardTitle")}
      dotColor="#2f9e8f"
    >
      <div className="mt-2 flex items-center gap-3 text-[12px] text-[var(--kq-color-muted)]">
        <StatChip icon={Layers} label={t("chat.flashcardStatsTotal")} value={stats.total} />
        <StatChip icon={Sparkles} label={t("chat.flashcardStatsDue")} value={stats.due} />
        <StatChip icon={Check} label={t("chat.flashcardStatsMature")} value={stats.mature} />
      </div>

      {mode === "review" && current ? (
        <div className="mt-3 grid gap-2">
          <div className="kq-workspace-card rounded-md px-3 py-3">
            <div className="text-[13px] font-medium text-[var(--kq-color-ink)] whitespace-pre-wrap break-words">
              {current.front}
            </div>
            {revealed ? (
              <div className="mt-2 border-t border-[var(--kq-color-border)] pt-2 text-[12.5px] leading-snug text-[var(--kq-color-ink)] whitespace-pre-wrap break-words">
                {current.back}
                {current.hint ? (
                  <div className="mt-1 text-[11.5px] text-[var(--kq-color-muted)]">
                    {t("chat.flashcardHint")}: {current.hint}
                  </div>
                ) : null}
              </div>
            ) : null}
          </div>
          <div className="text-right text-[11px] text-[var(--kq-color-muted)]">
            {t("chat.flashcardRemaining", { count: queue.length - index })}
          </div>
          {revealed ? (
            <div className="grid grid-cols-4 gap-1.5">
              {GRADES.map((g) => (
                <button
                  key={g.grade}
                  type="button"
                  onClick={() => grade(g.grade)}
                  className="kq-quick-action rounded-[10px] px-1 py-2 text-[12px] leading-snug transition"
                  style={{ color: g.tone }}
                >
                  {t(g.labelKey)}
                </button>
              ))}
            </div>
          ) : (
            <button
              type="button"
              onClick={() => setRevealed(true)}
              className="kq-quick-action rounded-[10px] px-2.5 py-2 text-[12.5px] leading-snug transition"
            >
              {t("chat.flashcardShowAnswer")}
            </button>
          )}
        </div>
      ) : null}

      {mode === "done" ? (
        <div className="mt-3 grid gap-2">
          <div className="rounded-md bg-[var(--kq-color-surface-2)] px-3 py-2 text-[12.5px] text-[var(--kq-color-ink)]">
            {t("chat.flashcardReviewDone")}
          </div>
          <button
            type="button"
            onClick={writeBack}
            disabled={wroteBack}
            className="kq-quick-action inline-flex items-center justify-center gap-1.5 rounded-[10px] px-2.5 py-2 text-[12.5px] leading-snug transition disabled:opacity-60"
          >
            <Check className="h-3.5 w-3.5" aria-hidden />
            {wroteBack ? t("chat.flashcardWroteBack") : t("chat.flashcardWriteBack")}
          </button>
        </div>
      ) : null}

      {mode === "idle" ? (
        <div className="mt-3 grid grid-cols-1 gap-2">
          <button
            type="button"
            onClick={startReview}
            disabled={stats.due === 0}
            className="kq-quick-action justify-start rounded-[10px] px-2.5 py-2 text-left text-[13px] leading-snug transition disabled:opacity-60"
          >
            <Sparkles className="kq-color-icon-course mr-2 inline h-4 w-4" aria-hidden />
            {stats.due > 0 ? t("chat.flashcardStartReview") : t("chat.flashcardNoDue")}
          </button>
          <button
            type="button"
            onClick={generate}
            className="kq-quick-action justify-start rounded-[10px] px-2.5 py-2 text-left text-[13px] leading-snug transition"
          >
            <Sparkles className="kq-color-icon-course mr-2 inline h-4 w-4" aria-hidden />
            {t("chat.flashcardGenerate")}
          </button>
          <button
            type="button"
            onClick={() => {
              setShowImport((v) => !v);
              setImportMsg("");
            }}
            className="kq-quick-action justify-start rounded-[10px] px-2.5 py-2 text-left text-[13px] leading-snug transition"
          >
            <Import className="kq-color-icon-course mr-2 inline h-4 w-4" aria-hidden />
            {t("chat.flashcardImportToggle")}
          </button>

          {showImport ? (
            <div className="grid gap-1.5">
              <textarea
                value={importText}
                onChange={(event) => setImportText(event.currentTarget.value)}
                placeholder={t("chat.flashcardImportPlaceholder")}
                rows={4}
                className="kq-workspace-select min-h-[64px] resize-none rounded-md px-2 py-1.5 text-[12px] leading-snug text-[var(--kq-color-ink)] transition"
              />
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={runImport}
                  disabled={!importText.trim()}
                  className="kq-quick-action inline-flex flex-1 items-center justify-center gap-1.5 rounded-[10px] px-2.5 py-2 text-[12.5px] leading-snug transition disabled:opacity-60"
                >
                  <Import className="h-3.5 w-3.5" aria-hidden />
                  {t("chat.flashcardImport")}
                </button>
                <button
                  type="button"
                  onClick={clearAll}
                  disabled={stats.total === 0}
                  className="kq-soft-icon-btn inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-md transition disabled:opacity-60"
                  aria-label={t("chat.flashcardClear")}
                  title={t("chat.flashcardClear")}
                >
                  <Eraser className="h-3.5 w-3.5" aria-hidden />
                </button>
              </div>
              {importMsg ? (
                <div className="text-[11.5px] text-[var(--kq-color-muted)]">{importMsg}</div>
              ) : null}
            </div>
          ) : null}
        </div>
      ) : null}
    </WorkspaceSection>
  );
}

function StatChip({
  icon: Icon,
  label,
  value,
}: {
  icon: LucideIcon;
  label: string;
  value: number;
}) {
  return (
    <span className="inline-flex items-center gap-1">
      <Icon className="h-3.5 w-3.5" aria-hidden />
      <span className="font-medium text-[var(--kq-color-ink)]">{value}</span>
      {label}
    </span>
  );
}
